name: Publish to rubygems
on:
  release:
    types: [published]
jobs:
  publish-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: |
          mkdir ~/.gem
          echo -e "---\r\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{secrets.rubygems_api_key}}
      - run: |
          gem build webpacker-electron.gemspec
          gem push webpacker-electron-*.gem
